import os


DEFAULT_BRIDGE_URL = os.environ.get("AIDELINK_DEFAULT_BRIDGE_URL", "http://127.0.0.1:5000")
DEFAULT_WOL_MAC = os.environ.get("AIDELINK_DEFAULT_WOL_MAC", "")
DEFAULT_FLASK_SERVICE_HOST = os.environ.get("AIDELINK_FLASK_SERVICE_HOST", "0.0.0.0")
DEFAULT_FLASK_SERVICE_PORT = int(os.environ.get("AIDELINK_FLASK_SERVICE_PORT", "5000"))
DEFAULT_OPENCODE_WEB_PORT = int(os.environ.get("AIDELINK_OPENCODE_WEB_PORT", "4096"))
